#
# ~/.config/alacritty/alacritty.toml
#

[general]
import = [
    "~/.config/alacritty/themes/themes/wombat.toml"
    # "~/.config/alacritty/themes/themes/Cobalt2.toml"
    # "~/.config/alacritty/themes/themes/challenger_deep.toml"
]

# For some reason this create a shell without proper path?
# [terminal]
# shell = { program = "/opt/homebrew/bin/zellij" }

[font]
size = 14

[font.normal]
family = "SauceCodePro Nerd Font"
# family = "JetbrainsMono Nerd Font"
# family = "FiraCode Nerd Font"

[window]
decorations = "None"
opacity = 0.9

# So zellij can use these
[keyboard]
bindings = [
    {key = "=", mods="Super", action = "IncreaseFontSize"},
    {key = "-", mods="Super", action = "DecreaseFontSize"},
    {key = "Return", mods="Shift", chars = "\u001B\r"},
]

