#
# ~/.config/alacritty/alacritty.toml
#

[general]
import = [
    "~/.config/alacritty/themes/themes/ayu_mirage.toml"
]

# For some reason this create a shell without proper path?
# [terminal]
# shell = { program = "/opt/homebrew/bin/zellij" }

[font]
size = 17

[font.normal]
family = "JetbrainsMono Nerd Font"

[window]
decorations = "Transparent"
opacity = 0.9
padding.x = 10
padding.y = 25

# So zellij can use these
[keyboard]
bindings = [
    {key = "n", mods="Command", action = "ReceiveChar"},
    {key = "i", mods="Command", action = "ReceiveChar"},
    # {key = "h", mods="Command", command = "zellij action move-focus left"},
    {key = "j", mods="Command", action = "ReceiveChar"},
    {key = "k", mods="Command", action = "ReceiveChar"},
    {key = "l", mods="Command", action = "ReceiveChar"},
    {key = "=", mods="Command", action = "ReceiveChar"},
    {key = "-", mods="Command", action = "ReceiveChar"},
    {key = "=", mods="Option", action = "IncreaseFontSize"},
    {key = "-", mods="Option", action = "DecreaseFontSize"},
]
